import './globals.css';
import { Inter } from 'next/font/google';
import FloatingShapes from './Home/component/FloatingShapes';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html>
        <head>
        </head>
        <body className='h-[100vh] w-[100vw] bg-[#b6b3a3] m-0 p-0 flex items-center justify-center font-nunito'>
        {children}            
        </body>
        </html>
  );
}
