import Link from 'next/link';
import './globals.css';
import { Inter } from 'next/font/google';
import FloatingShapes from './Home/component/FloatingShapes';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html>
      <head>
    </head>
    <body>
    {children}            
    </body>
    </html>
  );
}
